version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel-app
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_DATABASE: curd-app
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      #MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/www/database
    networks:
      - laravel

volumes:
  dbdata:
     
networks:
  laravel:
    driver: bridge
