apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-db
  template:
    metadata:
      labels:
        app: laravel-db
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_DATABASE
              value: laravel
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-storage
          emptyDir: {}  # Or use PersistentVolumeClaim
