apiVersion: v1
kind: Service
metadata:
  name: laravel-web
spec:
  type: NodePort
  selector:
    app: laravel-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Expose as http://localhost:30080
